pref("extensions.abpcustomization.vertical-preferences-layout", false);
pref("extensions.abpcustomization.preferences-one-line-subscriptions", false);
pref("extensions.abpcustomization.preferences-remove-checkbox-label", false);
pref("extensions.abpcustomization.preferences-remove-actions-button", false);
pref("extensions.abpcustomization.preferences-no-italics", false);
pref("extensions.abpcustomization.preferences-bold-titles", false);
pref("extensions.abpcustomization.toolbar-icon-display", 0);
pref("extensions.abpcustomization.green-icon", false);
pref("extensions.abpcustomization.remove-menus", false);
